Taste/Pages/Customer/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Pages.Customer.Cart
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderDetailsCartVM OrderDetailsCartVMObj { get; set; }
        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {
            OrderDetailsCartVMObj = new()
            {
                OrderHeader = new(),
                ListOfShoppingCart = new()
            };

            OrderDetailsCartVMObj.OrderHeader.OrderTotal = 0;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            IEnumerable<ShoppingCart> listOfShoppingCarts = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value);
            if (claim != null)
            {
                OrderDetailsCartVMObj.ListOfShoppingCart = listOfShoppingCarts.ToList();
                if(listOfShoppingCarts != null)
                {
                    OrderDetailsCartVMObj.ListOfShoppingCart = listOfShoppingCarts.ToList();
                }
                foreach (var cartList in OrderDetailsCartVMObj.ListOfShoppingCart)
                {
                    cartList.MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(c => c.Id == cartList.MenuItemId);
                    OrderDetailsCartVMObj.OrderHeader.OrderTotal += (cartList.MenuItem.Price * cartList.Count);
                }
            }
        }
        public IActionResult OnPostPlus(int id)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == id);
            if(cart != null)
            {
                _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
                _unitOfWork.Save();
                return RedirectToPage("/Customer/Cart/Index");
            }
            return Page();
        }
        public IActionResult OnPostMinus(int id)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == id);
            if (cart.Count == 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
                _unitOfWork.Save();

                var shoppingCardCount = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == cart.ApplicationUserId).ToList().Count();

                HttpContext.Session.SetInt32(SD.ShoppingCart, shoppingCardCount);
            }
            else
            {
                _unitOfWork.ShoppingCart.DecrementCount(cart, 1);
                _unitOfWork.Save();
            }
            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostRemove(int id)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == id);
            if (cart != null)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
                _unitOfWork.Save();

                var shoppingCardCount = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == cart.ApplicationUserId).ToList().Count();

                HttpContext.Session.SetInt32(SD.ShoppingCart, shoppingCardCount);
                return RedirectToPage("/Customer/Cart/Index");
            }
            return NotFound();
        }
    }
}

Taste/Pages/Customer/Cart/OrderConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taste.Pages.Customer.Cart
{
    public class OrderConfirmationModel : PageModel
    {
        [BindProperty]
        public int OrderId { get; set; }
        public void OnGet(int id)
        {
            OrderId = id;
        }
    }
}

Taste/Pages/Customer/Cart/Summary.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Pages.Customer.Cart
{
    public class SummaryModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderDetailsCartVM OrderDetailsCart { get; set; }
        public SummaryModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult OnGet()
        {
            OrderDetailsCart = new()
            {
                OrderHeader = new()
            };

            OrderDetailsCart.OrderHeader.OrderTotal = 0;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                IEnumerable<ShoppingCart> listOfShoppingCarts = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value);

                if (listOfShoppingCarts != null)
                {
                    OrderDetailsCart.ListOfShoppingCart = listOfShoppingCarts.ToList();
                }
                foreach (var cartList in OrderDetailsCart.ListOfShoppingCart)
                {
                    cartList.MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(c => c.Id == cartList.MenuItemId);
                    OrderDetailsCart.OrderHeader.OrderTotal += (cartList.MenuItem.Price * cartList.Count);
                }

                ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(a => a.Id == claim.Value);
                if (applicationUser != null)
                {
                    OrderDetailsCart.OrderHeader.PickupName = applicationUser.FullName;
                    OrderDetailsCart.OrderHeader.PickupTime = DateTime.Now;
                    OrderDetailsCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
                    return Page();
                }
                else
                {
                    return NotFound();
                }

            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult OnPost(string stripeToken)
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            OrderDetailsCart.ListOfShoppingCart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).ToList();

            OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            OrderDetailsCart.OrderHeader.OrderDate = DateTime.Now;
            OrderDetailsCart.OrderHeader.UserId = claim.Value;
            OrderDetailsCart.OrderHeader.Status = SD.PaymentStatusPending;
            OrderDetailsCart.OrderHeader.PickupTime = Convert.ToDateTime(OrderDetailsCart.OrderHeader.PickupDate.ToShortDateString() + " " +
                OrderDetailsCart.OrderHeader.PickupTime.ToShortTimeString());

            List<OrderDetail> orderDetailsList = new();
            _unitOfWork.OrderHeader.Add(OrderDetailsCart.OrderHeader);
            _unitOfWork.Save();
            foreach (var item in OrderDetailsCart.ListOfShoppingCart)
            {
                item.MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(u => u.Id == item.Id);
                OrderDetail orderDetail = new()
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = OrderDetailsCart.OrderHeader.Id,
                    Description = item.MenuItem.Description,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count
                };

                OrderDetailsCart.OrderHeader.OrderTotal += (orderDetail.Count * orderDetail.Price);
                _unitOfWork.OrderDetail.Add(orderDetail);

            }
            OrderDetailsCart.OrderHeader.OrderTotal = Convert.ToDouble(string.Format("{0:##}", OrderDetailsCart.OrderHeader.OrderTotal));

            _unitOfWork.ShoppingCart.RemoveRange(OrderDetailsCart.ListOfShoppingCart);
            HttpContext.Session.SetInt32(SD.ShoppingCart, 0);
            _unitOfWork.Save();

            if (stripeToken != null)
            {
                var options = new ChargeCreateOptions()
                {
                    //Amount is in cents...
                    Amount = Convert.ToInt32(OrderDetailsCart.OrderHeader.OrderTotal * 100),
                    Currency = "usd",
                    Description = "Order ID: " + OrderDetailsCart.OrderHeader.Id,
                    Source = stripeToken
                };

                var service = new ChargeService();
                Charge charge = service.Create(options);

                OrderDetailsCart.OrderHeader.TransactionId = charge.Id;

                if (charge.Status.ToLower() == "succeeded")
                {
                    //Email
                    OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
                    OrderDetailsCart.OrderHeader.Status = SD.StatusSubmitted;
                }
                else
                {
                    OrderDetailsCart.OrderHeader.Status = SD.PaymentStatusRejected;
                }
            }
            else
            {
                OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            }
            _unitOfWork.Save();
            return RedirectToPage("/Customer/Cart/OrderConfirmation", new { id = OrderDetailsCart.OrderHeader.Id });
        }
    }
}

Taste/Pages/Customer/Home/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using System.Security.Claims;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Utility;

namespace Taste.Pages.Customer.Home
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public DetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public ShoppingCart ShoppingCartObj { get; set; }
        public void OnGet(int id)
        {
            ShoppingCartObj = new()
            {
                MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(includedProperties: "Category,FoodType",
                filter: c => c.Id == id),
                MenuItemId = id
            };
        }

        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                ShoppingCartObj.ApplicationUserId = claim.Value;
                ShoppingCart shoppingCartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.ApplicationUserId == ShoppingCartObj.ApplicationUserId &&
                 c.MenuItemId == ShoppingCartObj.MenuItemId);

                if(shoppingCartFromDb == null)
                {
                    _unitOfWork.ShoppingCart.Add(ShoppingCartObj);
                }
                else
                {
                  _unitOfWork.ShoppingCart.IncrementCount(shoppingCartFromDb, ShoppingCartObj.Count);
                }
                _unitOfWork.Save();
                var count = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == ShoppingCartObj.ApplicationUserId).ToList().Count();
                HttpContext.Session.SetInt32(SD.ShoppingCart, count);
                return RedirectToPage("Index");
            }
            else
            {
                ShoppingCartObj.MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(includedProperties: "Category,FoodType",
                filter: c => c.Id == ShoppingCartObj.MenuItemId);
                return Page();
            }
        }
    }
}

Taste/Pages/Customer/Home/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Pages.Customer.Home
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public CustomerHomeVM CustomerHomeVM { get; set; } = new();
        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if(claim != null)
            {
                int shoppingCartCount = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).ToString().Count();

                HttpContext.Session.SetInt32(SD.ShoppingCart, shoppingCartCount);
            }

            CustomerHomeVM.ListOfMenuItems = _unitOfWork.MenuItem.GetAll(null, null, "Category,FoodType");
            CustomerHomeVM.ListOfCategorieItems = _unitOfWork.Category.GetAll(null, c => c.OrderBy(c => c.DisplayOrder), null);
         
        }
    }
}

Taste/Pages/Customer/Cart/Index.cshtml
@page
@model Taste.Pages.Customer.Cart.IndexModel
@{
    ViewData["Title"] = "Shopping Cart Details";
}


<form method="post">

    <br />
    @if (Model.OrderDetailsCartVMObj.ListOfShoppingCart.Any())
    {
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Shopping Cart
                        </div>
                        <div class="col-6 text-right">
                            <a class="btn btn-outline-info btn-sm" asp-page="../Home/Index">Continue Shopping</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.OrderDetailsCartVMObj.ListOfShoppingCart)
                        {
                            <input type="hidden" asp-for="@Model.OrderDetailsCartVMObj.ListOfShoppingCart[0].ApplicationUserId" />
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="@item.MenuItem.Image" class="rounded-circle" width="120" height="80" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4><strong>@item.MenuItem.Name</strong></h4>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>@item.MenuItem.Price.ToString("c")<span class="text-muted">x</span>@item.Count</strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-primary"
                                                    asp-route-id="@item.Id" asp-page-handler="plus">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-danger"
                                                    asp-route-id="@item.Id" asp-page-handler="minus">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <button type="submit" class="btn btn-outline-danger"
                                                asp-route-id="@item.Id" asp-page-handler="remove">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }




                        <div class="row">
                            <div class="col-12 col-md-5">

                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info"> Total (USD)</span>
                                        <strong class="text-info">$ <span id="txtOrderTotal">@Model.OrderDetailsCartVMObj.OrderHeader.OrderTotal</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <a asp-page="Summary" class="btn btn-success form-control">Summary</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div>Please add items to shopping cart.</div>
    }
</form>

Taste/Pages/Customer/Cart/OrderConfirmation.cshtml
@page
@model Taste.Pages.Customer.Cart.OrderConfirmationModel
@{
    ViewData["Title"] = "Order Confirmation";
}

<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-center text-primary">Order Placed Successful!</h1>
        Your Order Number is @Model.OrderId <br /><br/>
        <img src="~/images/lawn_leaf.jpg" style="width:65%"/>
    </div>
    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfuly
        <br />
        Please make sure to arrive on time for hot delcious food!
    </div>
</div>

Taste/Pages/Customer/Cart/Summary.cshtml
@page
@model Taste.Pages.Customer.Cart.SummaryModel
@inject IOptions<StripeSettings> _stripe
@{
    ViewData["Title"] = "Summary";
}

<form method="post">
    <br />
    @if (Model.OrderDetailsCart.ListOfShoppingCart.Any())
    {
        <input hidden asp-for="@Model.OrderDetailsCart.ListOfShoppingCart[0].ApplicationUserId" />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Order Summary
                        </div>
                        <div class="col-6 text-right">
                            <a asp-page="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">PickUp Details:</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderDetailsCart.OrderHeader.PickupName" id="txtName" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Phone Number</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderDetailsCart.OrderHeader.PhoneNumber" id="txtPhone" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Pickup Date</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderDetailsCart.OrderHeader.PickupDate" id="datepicker" value="" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Pickup Time</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderDetailsCart.OrderHeader.PickupTime" id="timepicker" value="" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Additional Instructions:</label>
                                        </div>
                                        <div class="col-9">
                                            <textarea asp-for="@Model.OrderDetailsCart.OrderHeader.Comments" id="comments" class="form-control" style="height:200px;"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Order Summary:</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        @{
                                            var total = 0.0;
                                        }
                                        @foreach (var details in Model.OrderDetailsCart.ListOfShoppingCart)
                                        {

                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@details.MenuItem.Name</h6>
                                                    <small class="text-muted">Quantity: @details.Count</small>
                                                </div>
                                                <span class="text-muted">$@(details.MenuItem.Price * details.Count)</span>
                                                @{
                                                    total += (details.MenuItem.Price * details.Count);
                                                }
                                            </li>

                                        }
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <small class="text-info">Total (USD)</small>
                                            <strong class="text-info">$@total.ToString("0.00")</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-md-8">
                                @{
                                    var orderTotalForStripe = Model.OrderDetailsCart.OrderHeader.OrderTotal * 100;
                                }
                                <script src="https://checkout.stripe.com/checkout.js"
                                        class="stripe-button"
                                        data-key="@_stripe.Value.PublishableKey"
                                        data-amount="@orderTotalForStripe"
                                        data-name="Taste Restaurant"
                                        data-label="Place Order"
                                        data-description="Good Food, Good Mood."
                                        data-locale="auto"
                                        data-allow-remember-me="false",
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                                        >
                                </script>
                                <script>
                                    document.getElementsByClassName('stripe-button-el')[0].style.display = "none";
                                </script>
                                <br />
                                <button type="submit" id="btn" onclick="return validateInput()" value="Place Order" class="btn btn-success form-control">Place Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {

    }
</form>

@section Scripts{
    <script>
        $(function () {
            $('#datepicker').datepicker({ minDate: 1, maxDate: '+1w' });
            $('#timepicker').timepicker({ minTime: '11:00 AM', maxTime: '9:00 PM', step: '30' });
        })

        function validateInput() {

            var name = document.getElementById('txtName').value;
            var phoneNumber = document.getElementById('txtPhone').value;
            var date = document.getElementById('datepicker').value;
            var time = document.getElementById('timepicker').value;

            if (date.toString() == '') {
                swal('Opps! error', 'Please select a pickup date', 'error');
                return false;
            }
            if (time.toString() == '') {
                swal('Opps! error', 'Please select a pickup time', 'error');
                return false;
            }
            if (phoneNumber.toString() == '') {
                swal('Opps! error', 'Please provide your contact', 'error');
                return false;
            }
            if (name.toString() == '') {
                swal('Opps! error', 'Please provide your name', 'error');
                return false;
            }

        }
    </script>

}