Taste/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Get(string status=null)
        {
            List<OrderDetailsViewModel> orderDetailsViewModels = new();
            IEnumerable<OrderHeader> orderHeaderList;


            if (User.IsInRole(SD.CustomerRole))
            {
                var claimIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
                orderHeaderList = _unitOfWork.OrderHeader.GetAll(x => x.UserId == claim.Value, null, "ApplicationUser");
            }
            else
            {
                orderHeaderList = _unitOfWork.OrderHeader.GetAll(null, null, "ApplicationUser");
            }

            if(status == "cancelled")
            {
                orderHeaderList = orderHeaderList.Where(o => o.Status == SD.StatusCancelled || o.Status == SD.StatusRefounded || o.Status == SD.PaymentStatusRejected);

            }
            else
            {
                if(status == "completed")
                {
                    orderHeaderList = orderHeaderList.Where(o => o.Status == SD.StatusCompleted);
                }
                else
                {
                    orderHeaderList = orderHeaderList.Where(o => o.Status == SD.StatusReady || o.Status == SD.StatusInProcess || o.Status == SD.StatusSubmitted || o.Status == SD.PaymentStatusPending);
                }
            }
            foreach (OrderHeader item in orderHeaderList)
            {
                OrderDetailsViewModel orderDetailsViewModel = new()
                {
                    OrderHeader = item,
                    OrderDetail = _unitOfWork.OrderDetail.GetAll(o => o.OrderId == item.Id).ToList()
                };

                orderDetailsViewModels.Add(orderDetailsViewModel);
            }

            return Json(new { data = orderDetailsViewModels });
        }
    }
}

Taste/Pages/Admin/Order/ManageOrder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Pages.Admin.Order
{
    public class ManageOrderModel : PageModel
    {

        private readonly IUnitOfWork _unitOfWork;
        public List<OrderDetailsViewModel> OrderDetailsVM { get; set; }
        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {
            OrderDetailsVM = new();
            List<OrderHeader> listOfOrderHeaders = _unitOfWork.OrderHeader.GetAll(o => o.Status == SD.StatusSubmitted || o.Status == SD.StatusInProcess)
                .OrderByDescending(o => o.PickupTime).ToList();

            foreach (var item in listOfOrderHeaders)
            {
                OrderDetailsViewModel model = new()
                {
                    OrderHeader = item,
                    OrderDetail = _unitOfWork.OrderDetail.GetAll(x => x.OrderId == item.Id).ToList()
                };

                OrderDetailsVM.Add(model);
            }
        }

        public IActionResult OnPostOrderPrepare(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if(orderHeader != null)
            {
                orderHeader.Status = SD.StatusInProcess;
                _unitOfWork.Save();
                return RedirectToPage("ManageOrder");
            }
            return Page();
        }
        public IActionResult OnPostOrderReady(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if (orderHeader != null)
            {
                orderHeader.Status = SD.StatusReady;
                _unitOfWork.Save();
                return RedirectToPage("ManageOrder");
            }
            return Page();
        }


        public IActionResult OnPostOrderCancel(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if (orderHeader != null)
            {
                orderHeader.Status = SD.StatusCancelled;
                _unitOfWork.Save();
                return RedirectToPage("ManageOrder");
            }
            return Page();
        }

        public IActionResult OnPostOrderRefund(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);

            var options = new RefundCreateOptions()
            {
                Amount = Convert.ToInt32(orderHeader.OrderTotal * 100),
                Reason = RefundReasons.RequestedByCustomer
            };
            var service = new RefundService();
            Refund refund = service.Create(options);

            orderHeader.Status = SD.StatusRefounded;
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
            //if (orderHeader != null)
            //{
            //    orderHeader.Status = SD.StatusRefounded;
            //    _unitOfWork.Save();
            //    return RedirectToPage("ManageOrder");
            //}
            //return Page();
            
        }
    }
}

Taste/Pages/Admin/Order/OrderDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;
using Taste.DataAccess.Data.Repository.IRepository;
using Taste.Models;
using Taste.Models.ViewModels;
using Taste.Utility;

namespace Taste.Pages.Admin.Order
{
    public class OrderDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderDetailsViewModel OrderDetailsViewModel { get; set; }
        public OrderDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet(int id)
        {
            OrderDetailsViewModel = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(x => x.OrderId == id).ToList()
            };

            OrderDetailsViewModel.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(a => a.Id == OrderDetailsViewModel.OrderHeader.UserId);
        }

        public IActionResult OnPostOrderConfirm(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if (orderHeader != null)
            {
                orderHeader.Status = SD.StatusCompleted;
                _unitOfWork.Save();
                return RedirectToPage("OrderList");
            }
            return Page();
        }
        public IActionResult OnPostOrderReady(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if (orderHeader != null)
            {
                orderHeader.Status = SD.StatusReady;
                _unitOfWork.Save();
                return RedirectToPage("OrderList");
            }
            return Page();
        }


        public IActionResult OnPostOrderCancel(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            if (orderHeader != null)
            {
                orderHeader.Status = SD.StatusCancelled;
                _unitOfWork.Save();
                return RedirectToPage("OrderList");
            }
            return Page();
        }

        public IActionResult OnPostOrderRefund(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);

            var options = new RefundCreateOptions()
            {
                Amount = Convert.ToInt32(orderHeader.OrderTotal * 100),
                Reason = RefundReasons.RequestedByCustomer
            };
            var service = new RefundService();
            Refund refund = service.Create(options);

            orderHeader.Status = SD.StatusRefounded;
            _unitOfWork.Save();
            return RedirectToPage("OrderList");

        }
    }
}

Taste/Pages/Admin/Order/OrderList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taste.Pages.Admin.Order
{
    public class OrderListModel : PageModel
    {
        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

Taste/Pages/Admin/Order/ManageOrder.cshtml
@page
@model Taste.Pages.Admin.Order.ManageOrderModel
@{
    ViewData["Title"] = "Manage Order";
}


<h1 class="text-primary py-3">Manage Order's</h1>
<form method="post">

    @if (Model.OrderDetailsVM.Count >0)
    {
        foreach (var item in Model.OrderDetailsVM)
        {
            <div class="container row bg-white p-2 border mb-3 rounded">

                <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
                    <div class="backgroundWhiteBorder10Padding">
                        <div class="row">
                            <div class="col-4">
                                Order Number : @item.OrderHeader.Id
                                <ul class="text-info">
                                    @foreach (var details in item.OrderDetail)
                                    {
                                        <li>@details.Name x @details.Count</li>
                                    }


                                </ul>
                            </div>
                            <div class="col-4 pb-2">
                                <div class="input-group pb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text">Time</span>
                                    </div>
                                    <input type="text" class="border rounded form-control" readonly value="@item.OrderHeader.PickupTime" />
                                </div>
                                @{
                                    var comments = item.OrderHeader.Comments;
                                    if (comments == null || comments.Trim().Length == 0)
                                    {
                                        item.OrderHeader.Comments = "No Instructions!";
                                    }
                                }
                                <textarea asp-for="@item.OrderHeader.Comments" readonly class="rounded border form-control" style="width:100%;height:75px;"></textarea>
                            </div>
                            <div class="col-3 offset-1 d-flex align-content-center">
                                <div class="col-12">
                                    @*<button type="submit" class="btn btn-primary form-control mb-3"
                                                asp-page-handler="orderprepare" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-check"></i>Start Cooking
                                        </button>
                                        <button type="submit" class="btn btn-success form-control mb-3"
                                                asp-page-handler="orderready" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-flag-checkered"></i> &nbsp; Order Ready
                                        </button>
                                        <button type="submit" class="btn btn-warning form-control mb-3"
                                                asp-page-handler="ordercancel" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-times"></i> &nbsp; Cancel Order
                                        </button>
                                        <button type="submit" class="btn btn-danger form-control mb-3"
                                                asp-page-handler="orderrefund" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-times"></i> &nbsp; Refund Order
                                        </button>*@

                                    @if (item.OrderHeader.Status == SD.StatusSubmitted)
                                    {
                                        <button type="submit" class="btn btn-primary form-control mb-3"
                                                asp-page-handler="orderprepare" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-check"></i>Start Cooking
                                        </button>
                                    }
                                    else if (item.OrderHeader.Status == SD.StatusInProcess)
                                    {
                                        <button type="submit" class="btn btn-success form-control mb-3"
                                                asp-page-handler="orderready" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-flag-checkered"></i> &nbsp; Order Ready
                                        </button>
                                    }
                                    else
                                    {

                                        <button type="submit" class="btn btn-warning form-control mb-3"
                                                asp-page-handler="ordercancel" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-times"></i> &nbsp; Cancel Order
                                        </button>
                                        <button type="submit" class="btn btn-danger form-control mb-3"
                                                asp-page-handler="orderrefund" asp-route-id="@item.OrderHeader.Id">
                                            <i class="fas fa-times"></i> &nbsp; Refund Order
                                        </button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        }
    }
    else
    {
        <div>No Items to display!</div>
    }

</form>

Taste/Pages/Admin/Order/OrderDetails.cshtml
@page
@model Taste.Pages.Admin.Order.OrderDetailsModel
@{
    ViewData["Title"] = "Order Details";
}


<form method="post">
    <div class="border ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">Order Details</p>
            </div>
            <div class="col-12 col-md-4 offset-md-2">
                <a class="btn btn-success form-control" asp-page="/Admin/Order/OrderList">Back to Orders </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">
            <input type="hidden" asp-for="OrderDetailsViewModel.OrderHeader.Id" />
            <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.PickupName"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.PickupName" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.ApplicationUser.Email"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.ApplicationUser.Email" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.PhoneNumber"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.PhoneNumber" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.OrderTotal"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.OrderTotal" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.OrderDate"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.OrderDate" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsViewModel.OrderHeader.Comments"></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderDetailsViewModel.OrderHeader.Comments" />
                    </div>
                </div>
            </div>



            <div class="col-lg-4 col-12">
                <h4 class="d-flex justify-content-between align-content-center mb-3">
                    <span class="text-muted">Order ID: </span>
                    <span class="badge badge-secondary badge-pill">@Model.OrderDetailsViewModel.OrderHeader.Id</span>
                </h4>
                <ul class="list-group mb-3">
                    @if (Model.OrderDetailsViewModel.OrderDetail != null)
                    {
                        @foreach (var item in Model.OrderDetailsViewModel.OrderDetail)
                        {
                            <li class="list-group-item d-flex justify-content-between">
                                <div>
                                    <h6 class="my-0">@item.Name</h6>
                                    <small class="text-muted">Quantity : @item.Count.ToString("c")</small>
                                </div>
                                <span class="text-muted">@(item.Price * item.Count)</span>
                            </li>


                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <span class="text-info"> Total (USD)</span>
                                <strong class="text-info">@Model.OrderDetailsViewModel.OrderHeader.OrderTotal</strong>
                            </li>
                        }

                    }

                </ul>
                @if (Model.OrderDetailsViewModel.OrderHeader.Status != null)
                {
                    @if (Model.OrderDetailsViewModel.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerRole)))
                    {
                        <button type="submit" asp-page-handler="orderconfirm" asp-route-id="@Model.OrderDetailsViewModel.OrderHeader.Id" class="btn btn-success form-control">
                            <i class="far fa-thumbs-up"></i>
                            Confirm Pickup
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-info form-control">
                            <i class="far fa-thumbs-up"></i>
                            @Model.OrderDetailsViewModel.OrderHeader.Status
                        </button>

                    }
                }
                @if (User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole) && (Model.OrderDetailsViewModel.OrderHeader.Status.Equals(SD.StatusSubmitted) || Model.OrderDetailsViewModel.OrderHeader.Status.Equals(SD.StatusReady) || Model.OrderDetailsViewModel.OrderHeader.Status.Equals(SD.StatusInProcess)))
                {
                    <div class="row mt-2">
                        <div class="col-6">
                            <button type="submit" asp-page-handler="ordercancel" asp-route-id="@Model.OrderDetailsViewModel.OrderHeader.Id" class="btn btn-warning form-control">
                                <i class="fas fa-times"></i>
                                Cancel Order
                            </button>
                        </div>
                        <div class="col-6">
                            <button type="submit" asp-page-handler="orderrefund" asp-route-id="@Model.OrderDetailsViewModel.OrderHeader.Id" class="btn btn-danger form-control">
                                <i class="fas fa-times"></i>
                                Refund Order
                            </button>
                        </div>
                    </div>


                }

            </div>

        </div>
    </div>
</form>

Taste/Pages/Admin/Order/OrderList.cshtml
@page
@model Taste.Pages.Admin.Order.OrderListModel
@{
    ViewData["Title"] = "Order List";
}

@{
    var status = HttpContext.Request.Query["status"];
    var cancelled = "text-primary";
    var completed = "text-primary";
    var inProcess = "text-primary";

    if (status == "cancelled")
    {
        cancelled = "active text-white";
    }
    else if (status == "completed")
    {
        completed = "active text-white";
    }
    else 
    {
        inProcess = "active text-white";
    }

}

<div class="border backgroundWhite container">
    <div class="d-flex justify-content-between mb-3">
        <div class="p-2">
            <h2 class="text-primary">Order's List</h2>
        </div>

        <div class="p-2">
            <ul class="list-group list-group-horizontal-sm">

                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="cancelled">
                    <li class="list-group-item @cancelled">Cancelled</li>
                </a>
                <a  style="text-decoration:none;" asp-page="OrderList" asp-route-status="completed">
                    <li class="list-group-item @completed">Completed</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="inProcess">
                    <li class="list-group-item @inProcess">InProcess</li>
                </a>

            </ul>
        </div>
    </div>
    <br /><br />
    <table id="DT_load" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Order Id</th>
                <th>Name</th>
                <th>Order Total</th>
                <th>Email</th>
                <th>Order Date</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>


@section Scripts{
    <script src="~/js/orderList.js"></script>
}